version: '3.5'
services:
  db: # Banco de dados
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: local123
      POSTGRES_USER: local
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '2.25GB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5